import { randomUUID } from "node:crypto";
import { task } from "@trigger.dev/sdk";
import {
  CHARACTER_REFERENCE_PROMPT_TEMPLATE_SOURCE_HASH,
  CHARACTER_REFERENCE_PROMPT_VERSION,
} from "@studio/prompts";
import { z } from "zod";
import {
  claimCharacterReferenceGenerationRunning,
  completeCharacterReferenceGeneration,
  failCharacterReferenceGeneration,
} from "@/db/commands/character-reference-generation.command";
import { findCharacterReferenceGeneration } from "@/db/repositories/character-reference-generation.repository";
import { findPromptTemplateVersion } from "@/db/repositories/scene-images.repository";
import {
  calculateActualSceneImageCostCents,
  reconcileSceneImageCost,
} from "@/lib/costs/scene-image-cost";
import { getSceneImageEnvironment } from "@/lib/env/server";
import { classifyImageGenerationError } from "@/lib/openai/image-generation-error";
import { OpenAiImageGenerationProvider } from "@/lib/openai/openai-image-generation-provider";
import { createCharacterReferenceObjectKey } from "@/lib/storage/object-key";
import {
  deleteCharacterReferenceObject,
  putCharacterReferenceImage,
} from "@/lib/storage/character-reference-storage";

export const characterReferenceGenerationTaskPayloadSchema = z.object({
  generationId: z.uuid(),
  workspaceId: z.uuid(),
  characterId: z.uuid(),
});

type CharacterReferenceTaskPayload = z.infer<
  typeof characterReferenceGenerationTaskPayloadSchema
>;

export const characterReferenceGenerationTask = task({
  id: "character-reference-generation",
  queue: { name: "image-generation", concurrencyLimit: 1 },
  // A provider outcome is not idempotent and portraits are cheap and manual, so
  // the request is never auto-repeated; a failed portrait is regenerated by the
  // user instead of risking a double charge.
  retry: { maxAttempts: 1 },
  maxDuration: 600,
  run: async (payload: CharacterReferenceTaskPayload) => {
    const input = characterReferenceGenerationTaskPayloadSchema.parse(payload);
    const environment = getSceneImageEnvironment();
    const scope = {
      workspaceId: input.workspaceId,
      generationId: input.generationId,
    };

    const generation = await findCharacterReferenceGeneration(scope);
    if (!generation)
      throw new Error("CHARACTER_REFERENCE_GENERATION_NOT_FOUND");
    if (generation.status === "succeeded")
      return { generationId: generation.id, status: "succeeded" as const };
    if (generation.status === "failed")
      return { generationId: generation.id, status: "failed" as const };

    if (!environment.ENABLE_SCENE_IMAGE_GENERATION) {
      await failCharacterReferenceGeneration({
        ...scope,
        safeErrorMessage: "Image generation is currently disabled.",
      });
      return { generationId: generation.id, status: "failed" as const };
    }

    const promptTemplate = await findPromptTemplateVersion({
      templateKey: "character-reference",
      version: generation.promptTemplateVersion,
    });
    if (
      !promptTemplate ||
      promptTemplate.id !== generation.promptTemplateVersionId ||
      promptTemplate.version !== CHARACTER_REFERENCE_PROMPT_VERSION ||
      promptTemplate.sourceHash !==
        CHARACTER_REFERENCE_PROMPT_TEMPLATE_SOURCE_HASH
    ) {
      await failCharacterReferenceGeneration({
        ...scope,
        safeErrorMessage:
          "The versioned portrait prompt template could not be verified, so no provider request was made.",
      });
      return { generationId: generation.id, status: "failed" as const };
    }

    const claim = await claimCharacterReferenceGenerationRunning({
      ...scope,
      providerRequestId: randomUUID(),
      attemptNumber: generation.attemptCount + 1,
    });
    if (!claim.claimed) {
      if (claim.generation.status === "succeeded")
        return { generationId: generation.id, status: "succeeded" as const };
      // A prior attempt already started but did not finish cleanly; do not risk
      // a second billable request.
      await failCharacterReferenceGeneration({
        ...scope,
        safeErrorMessage:
          "The previous portrait attempt did not complete. Generate a new portrait to try again.",
      });
      return { generationId: generation.id, status: "failed" as const };
    }

    const provider = new OpenAiImageGenerationProvider({
      apiKey: environment.OPENAI_API_KEY,
      timeoutMilliseconds: environment.OPENAI_REQUEST_TIMEOUT_SECONDS * 1_000,
    });
    let result: Awaited<ReturnType<typeof provider.generate>>;
    try {
      result = await provider.generate({
        model: generation.model,
        prompt: generation.finalPrompt,
        quality: z.enum(["low", "medium", "high"]).parse(generation.quality),
        size: z
          .enum(["1536x1024", "1024x1536", "1024x1024"])
          .parse(generation.size),
        outputFormat: z
          .enum(["webp", "png", "jpeg"])
          .parse(generation.outputFormat),
        outputCompression: generation.outputCompression,
        background: z.enum(["opaque", "auto"]).parse(generation.background),
        endUserId: generation.requestedByUserId,
        references: [],
      });
    } catch (error) {
      const failure = classifyImageGenerationError(error);
      console.error("Character reference generation failed.", {
        generationId: generation.id,
        error: error instanceof Error ? (error.stack ?? error.message) : error,
      });
      await failCharacterReferenceGeneration({
        ...scope,
        safeErrorMessage: failure.safeMessage,
        actualCostCents: failure.providerMayHaveAcceptedRequest
          ? generation.estimatedCostCents
          : 0,
      });
      return { generationId: generation.id, status: "failed" as const };
    }

    const actualCostFromUsage = result.usage
      ? calculateActualSceneImageCostCents({
          usage: result.usage,
          rates: {
            textInputCostPerMillionCents:
              environment.OPENAI_IMAGE_TEXT_INPUT_COST_PER_MILLION_CENTS,
            imageInputCostPerMillionCents:
              environment.OPENAI_IMAGE_INPUT_COST_PER_MILLION_CENTS,
            outputCostPerMillionCents:
              environment.OPENAI_IMAGE_OUTPUT_COST_PER_MILLION_CENTS,
          },
        })
      : null;
    const reconciliation = reconcileSceneImageCost({
      reservedCostCents: generation.estimatedCostCents,
      actualCostCents: actualCostFromUsage,
    });

    const objectKey = createCharacterReferenceObjectKey({
      workspaceId: generation.workspaceId,
      characterId: generation.characterId,
      referenceType: generation.referenceType,
      contentType: result.mimeType,
    });

    let stored;
    try {
      stored = await putCharacterReferenceImage({
        objectKey,
        bytes: result.bytes,
        contentType: result.mimeType,
        width: result.width,
        height: result.height,
      });
    } catch {
      await failCharacterReferenceGeneration({
        ...scope,
        safeErrorMessage:
          "The generated portrait could not be saved. Generate a new portrait to try again.",
        actualCostCents: reconciliation.chargedCostCents,
      });
      return { generationId: generation.id, status: "failed" as const };
    }

    const { previous } = await completeCharacterReferenceGeneration({
      workspaceId: generation.workspaceId,
      characterId: generation.characterId,
      generationId: generation.id,
      referenceType: generation.referenceType,
      actualCostCents: reconciliation.chargedCostCents,
      asset: {
        objectKey: stored.objectKey,
        contentType: stored.contentType,
        sizeBytes: stored.sizeBytes,
        width: stored.width,
        height: stored.height,
        etag: stored.etag,
      },
      createdByUserId: generation.requestedByUserId,
    });

    if (previous)
      await deleteCharacterReferenceObject(previous.objectKey).catch(() => {});

    return { generationId: generation.id, status: "succeeded" as const };
  },
});
