import { randomUUID } from "node:crypto";
import { task } from "@trigger.dev/sdk";
import {
  CHARACTER_REFERENCE_PROMPT_TEMPLATE_SOURCE_HASH,
  CHARACTER_REFERENCE_PROMPT_VERSION,
} from "@studio/prompts";
import { z } from "zod";
import {
  claimCharacterReferenceGenerationRunning,
  completeCharacterReferenceGeneration,
  failCharacterReferenceGeneration,
} from "@/db/commands/character-reference-generation.command";
import { findCharacterReferenceGeneration } from "@/db/repositories/character-reference-generation.repository";
import { listCharacterReferences } from "@/db/repositories/characters.repository";
import { findPromptTemplateVersion } from "@/db/repositories/scene-images.repository";
import {
  calculateActualSceneImageCostCents,
  reconcileSceneImageCost,
} from "@/lib/costs/scene-image-cost";
import { getSceneImageEnvironment } from "@/lib/env/server";
import { classifyImageGenerationError } from "@/lib/openai/image-generation-error";
import type { ImageGenerationReference } from "@/lib/openai/image-generation-provider";
import { OpenAiImageGenerationProvider } from "@/lib/openai/openai-image-generation-provider";
import { createCharacterReferenceObjectKey } from "@/lib/storage/object-key";
import {
  deleteCharacterReferenceObject,
  putCharacterReferenceImage,
} from "@/lib/storage/character-reference-storage";
import { downloadSceneImageReferences } from "@/lib/storage/scene-image-storage";
import {
  sceneImageApiSizeSchema,
  sceneImageBackgroundSchema,
  sceneImageOutputFormatSchema,
  sceneImageQualitySchema,
} from "@/lib/schemas/scene-image";

// Every portrait — identity views and animation poses alike — is generated as
// an edit anchored to the character's own already-uploaded/generated
// reference images, not from text alone. Master and front are prioritized
// (they carry the clearest identity signal); everything else the character
// has (expression, outfit, other views, other poses) fills the remaining
// slots up to the configured per-generation cap, most recent first.
const referencePriorityTypes = ["master", "front"];

async function resolveCharacterReferenceInputs(input: {
  workspaceId: string;
  characterId: string;
  maximumCount: number;
  maximumTotalBytes: number;
}): Promise<ImageGenerationReference[]> {
  const existing = await listCharacterReferences({
    workspaceId: input.workspaceId,
    characterId: input.characterId,
  });
  if (existing.length === 0) return [];

  // `listCharacterReferences` already orders most-recent-first; a stable sort
  // that only promotes master/front preserves that recency order otherwise.
  const prioritized = [...existing].sort((left, right) => {
    const leftRank = referencePriorityTypes.indexOf(left.type);
    const rightRank = referencePriorityTypes.indexOf(right.type);
    if (leftRank === rightRank) return 0;
    if (leftRank === -1) return 1;
    if (rightRank === -1) return -1;
    return leftRank - rightRank;
  });
  const selected = prioritized.slice(0, input.maximumCount);

  return downloadSceneImageReferences({
    references: selected.map((asset) => ({
      referenceAssetIdSnapshot: asset.id,
      objectKeySnapshot: asset.objectKey,
      contentTypeSnapshot: asset.contentType,
      etagSnapshot: asset.etag ?? "",
    })),
    maximumTotalBytes: input.maximumTotalBytes,
  }).catch((error: unknown) => {
    // A reference-fetch failure (e.g. a legacy asset missing its etag) must
    // not block the whole portrait; it degrades to a text-only generation
    // rather than failing the request outright.
    console.error(
      "Character reference inputs could not be resolved; generating without them.",
      {
        workspaceId: input.workspaceId,
        characterId: input.characterId,
        error: error instanceof Error ? error.message : error,
      },
    );
    return [];
  });
}

export const characterReferenceGenerationTaskPayloadSchema = z.object({
  generationId: z.uuid(),
  workspaceId: z.uuid(),
  characterId: z.uuid(),
});

type CharacterReferenceTaskPayload = z.infer<
  typeof characterReferenceGenerationTaskPayloadSchema
>;

export const characterReferenceGenerationTask = task({
  id: "character-reference-generation",
  queue: { name: "image-generation", concurrencyLimit: 1 },
  // A provider outcome is not idempotent and portraits are cheap and manual, so
  // the request is never auto-repeated; a failed portrait is regenerated by the
  // user instead of risking a double charge.
  retry: { maxAttempts: 1 },
  maxDuration: 600,
  run: async (payload: CharacterReferenceTaskPayload) => {
    const input = characterReferenceGenerationTaskPayloadSchema.parse(payload);
    const environment = getSceneImageEnvironment();
    const scope = {
      workspaceId: input.workspaceId,
      generationId: input.generationId,
    };

    const generation = await findCharacterReferenceGeneration(scope);
    if (!generation)
      throw new Error("CHARACTER_REFERENCE_GENERATION_NOT_FOUND");
    if (generation.status === "succeeded")
      return { generationId: generation.id, status: "succeeded" as const };
    if (generation.status === "failed")
      return { generationId: generation.id, status: "failed" as const };

    if (!environment.ENABLE_SCENE_IMAGE_GENERATION) {
      await failCharacterReferenceGeneration({
        ...scope,
        safeErrorMessage: "Image generation is currently disabled.",
      });
      return { generationId: generation.id, status: "failed" as const };
    }

    const promptTemplate = await findPromptTemplateVersion({
      templateKey: "character-reference",
      version: generation.promptTemplateVersion,
    });
    if (
      !promptTemplate ||
      promptTemplate.id !== generation.promptTemplateVersionId ||
      promptTemplate.version !== CHARACTER_REFERENCE_PROMPT_VERSION ||
      promptTemplate.sourceHash !==
        CHARACTER_REFERENCE_PROMPT_TEMPLATE_SOURCE_HASH
    ) {
      await failCharacterReferenceGeneration({
        ...scope,
        safeErrorMessage:
          "The versioned portrait prompt template could not be verified, so no provider request was made.",
      });
      return { generationId: generation.id, status: "failed" as const };
    }

    const claim = await claimCharacterReferenceGenerationRunning({
      ...scope,
      providerRequestId: randomUUID(),
      attemptNumber: generation.attemptCount + 1,
    });
    if (!claim.claimed) {
      if (claim.generation.status === "succeeded")
        return { generationId: generation.id, status: "succeeded" as const };
      // A prior attempt already started but did not finish cleanly; do not risk
      // a second billable request.
      await failCharacterReferenceGeneration({
        ...scope,
        safeErrorMessage:
          "The previous portrait attempt did not complete. Generate a new portrait to try again.",
      });
      return { generationId: generation.id, status: "failed" as const };
    }

    const referenceInputs = await resolveCharacterReferenceInputs({
      workspaceId: generation.workspaceId,
      characterId: generation.characterId,
      maximumCount: environment.MAX_REFERENCE_ASSETS_PER_GENERATION,
      maximumTotalBytes: environment.MAX_REFERENCE_BYTES_PER_GENERATION,
    });

    const provider = new OpenAiImageGenerationProvider({
      apiKey: environment.OPENAI_API_KEY,
      timeoutMilliseconds: environment.OPENAI_REQUEST_TIMEOUT_SECONDS * 1_000,
    });
    let result: Awaited<ReturnType<typeof provider.generate>>;
    try {
      result = await provider.generate({
        model: generation.model,
        prompt: generation.finalPrompt,
        // Parsed through the shared scene-image schemas rather than inline
        // enums: these columns are plain `text`, and a local copy of the
        // allowed values silently goes stale (transparent pose backgrounds
        // were rejected here for exactly that reason).
        quality: sceneImageQualitySchema.parse(generation.quality),
        size: sceneImageApiSizeSchema.parse(generation.size),
        outputFormat: sceneImageOutputFormatSchema.parse(
          generation.outputFormat,
        ),
        outputCompression: generation.outputCompression,
        background: sceneImageBackgroundSchema.parse(generation.background),
        endUserId: generation.requestedByUserId,
        references: referenceInputs,
      });
    } catch (error) {
      const failure = classifyImageGenerationError(error);
      console.error("Character reference generation failed.", {
        generationId: generation.id,
        error: error instanceof Error ? (error.stack ?? error.message) : error,
      });
      await failCharacterReferenceGeneration({
        ...scope,
        safeErrorMessage: failure.safeMessage,
        actualCostCents: failure.providerMayHaveAcceptedRequest
          ? generation.estimatedCostCents
          : 0,
      });
      return { generationId: generation.id, status: "failed" as const };
    }

    const actualCostFromUsage = result.usage
      ? calculateActualSceneImageCostCents({
          usage: result.usage,
          rates: {
            textInputCostPerMillionCents:
              environment.OPENAI_IMAGE_TEXT_INPUT_COST_PER_MILLION_CENTS,
            imageInputCostPerMillionCents:
              environment.OPENAI_IMAGE_INPUT_COST_PER_MILLION_CENTS,
            outputCostPerMillionCents:
              environment.OPENAI_IMAGE_OUTPUT_COST_PER_MILLION_CENTS,
          },
        })
      : null;
    const reconciliation = reconcileSceneImageCost({
      reservedCostCents: generation.estimatedCostCents,
      actualCostCents: actualCostFromUsage,
    });

    const objectKey = createCharacterReferenceObjectKey({
      workspaceId: generation.workspaceId,
      characterId: generation.characterId,
      referenceType: generation.referenceType,
      contentType: result.mimeType,
    });

    let stored;
    try {
      stored = await putCharacterReferenceImage({
        objectKey,
        bytes: result.bytes,
        contentType: result.mimeType,
        width: result.width,
        height: result.height,
      });
    } catch {
      await failCharacterReferenceGeneration({
        ...scope,
        safeErrorMessage:
          "The generated portrait could not be saved. Generate a new portrait to try again.",
        actualCostCents: reconciliation.chargedCostCents,
      });
      return { generationId: generation.id, status: "failed" as const };
    }

    const { previous } = await completeCharacterReferenceGeneration({
      workspaceId: generation.workspaceId,
      characterId: generation.characterId,
      generationId: generation.id,
      referenceType: generation.referenceType,
      actualCostCents: reconciliation.chargedCostCents,
      asset: {
        objectKey: stored.objectKey,
        contentType: stored.contentType,
        sizeBytes: stored.sizeBytes,
        width: stored.width,
        height: stored.height,
        etag: stored.etag,
      },
      createdByUserId: generation.requestedByUserId,
    });

    if (previous)
      await deleteCharacterReferenceObject(previous.objectKey).catch(() => {});

    return { generationId: generation.id, status: "succeeded" as const };
  },
});
