import type { ThumbnailGeneration } from "@/db/schema";

/**
 * The parameters of a thumbnail that was actually generated by a provider.
 *
 * A thumbnail row now describes one of two things: an image a provider was paid
 * to make, or an image the creator already had and uploaded. Only the first has
 * a prompt, a model and a fingerprint, and those columns are nullable because
 * filling them with placeholders for an upload would put a reproducible-looking
 * generation in the ledger that nobody can reproduce.
 *
 * This narrows the row once, so callers that need those values cannot reach for
 * them without having established that they exist.
 */
export interface ThumbnailGenerationRequest {
  textMode: NonNullable<ThumbnailGeneration["textMode"]>;
  finalPrompt: string;
  requestFingerprint: string;
  model: string;
  quality: NonNullable<ThumbnailGeneration["quality"]>;
  outputCompression: number;
}

export function describeThumbnailGenerationRequest(
  generation: Pick<
    ThumbnailGeneration,
    | "source"
    | "textMode"
    | "finalPrompt"
    | "requestFingerprint"
    | "model"
    | "quality"
    | "outputCompression"
  >,
): ThumbnailGenerationRequest | null {
  if (generation.source !== "ai_generated") return null;
  const {
    textMode,
    finalPrompt,
    requestFingerprint,
    model,
    quality,
    outputCompression,
  } = generation;
  // All or nothing. A database constraint enforces the same rule, so a partial
  // row means something has bypassed it and must not reach a paid provider.
  if (
    textMode === null ||
    finalPrompt === null ||
    requestFingerprint === null ||
    model === null ||
    quality === null ||
    outputCompression === null
  )
    return null;
  return {
    textMode,
    finalPrompt,
    requestFingerprint,
    model,
    quality,
    outputCompression,
  };
}

/**
 * How a thumbnail should be described in the gallery.
 *
 * An uploaded image is never described by a text mode: nobody asked a model for
 * text, so "text-free" would be a claim about the file's contents that has not
 * been checked.
 */
export function describeThumbnailOrigin(
  thumbnail: Pick<ThumbnailGeneration, "source" | "textMode" | "headlineText">,
): string {
  if (thumbnail.source === "user_uploaded") return "Uploaded";
  if (thumbnail.textMode === "baked") return "Headline baked in";
  if (thumbnail.textMode === "clean") return "Text-free";
  return "Generated";
}
